/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3728fdb0-146c-4d43-bb1e-3e28a2ba337d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_melVPCyAG",
    "aws_user_pools_web_client_id": "ku28bt1fhims4k5helubmnedq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cisc498resistorreade30752ff084f9419aa526a917e4292158-final",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
