/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d4ea6fd3-178d-4598-8009-d5f33358bf60",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HdOGY9N4Y",
    "aws_user_pools_web_client_id": "37t0o5ttagdj7t6ehr69918vkv",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cisc498resistorreade30752ff084f9419aa526a917e42111301-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
